UPDATE technos SET type = 'fullstack' WHERE name IN ('TypeScript', 'Laravel', 'Symfony');

INSERT INTO technos (name, type) VALUES
  ('JavaScript', 'front'),
  ('HTML', 'front'),
  ('CSS', 'front'),
  ('Sass', 'front'),
  ('Less', 'front'),
  ('Stylus', 'front'),
  ('PostCSS', 'front'),
  ('Tailwind CSS', 'front'),
  ('Bootstrap', 'front'),
  ('Bulma', 'front'),
  ('Foundation', 'front'),
  ('Materialize', 'front'),
  ('Material UI', 'front'),
  ('Ant Design', 'front'),
  ('Vuetify', 'front'),
  ('Angular Material', 'front'),
  ('React Bootstrap', 'front'),
  ('AngularJS', 'front'),
  ('Svelte', 'front'),
  ('SolidJS', 'front'),
  ('Qwik', 'front'),
  ('Alpine.js', 'front'),
  ('jQuery', 'front'),
  ('Backbone.js', 'front'),
  ('Ember.js', 'front'),
  ('Knockout', 'front'),
  ('Mithril', 'front'),
  ('Elm', 'front'),
  ('Redux', 'front'),
  ('MobX', 'front'),
  ('NgRx', 'front'),
  ('RxJS', 'front'),
  ('React Router', 'front'),
  ('React Navigation', 'front'),
  ('Framer Motion', 'front'),
  ('Three.js', 'front'),
  ('D3.js', 'front'),
  ('p5.js', 'front'),
  ('Swiper', 'front'),
  ('Axios', 'front'),
  ('Gatsby', 'front'),
  ('Astro', 'front'),
  ('Eleventy', 'front'),
  ('Hugo', 'front'),
  ('Jekyll', 'front'),
  ('Storybook', 'front'),
  ('Vite', 'front'),
  ('Webpack', 'front'),
  ('Rollup', 'front'),
  ('Babel', 'front'),
  ('Gulp', 'front'),
  ('Grunt', 'front'),
  ('Cypress', 'front'),
  ('Playwright', 'front'),
  ('Vitest', 'front'),
  ('Jasmine', 'front'),
  ('Karma', 'front'),
  ('Protractor', 'front'),
  ('Flutter', 'front'),
  ('Dart', 'front'),
  ('Ionic', 'front'),
  ('Capacitor', 'front'),
  ('Swift', 'front'),
  ('Objective-C', 'front'),
  ('Jetpack Compose', 'front'),
  ('Xamarin', 'front'),
  ('Framework7', 'front'),
  ('Quasar', 'front'),
  ('Electron', 'front'),
  ('Tauri', 'front'),
  ('CoffeeScript', 'front'),
  ('PureScript', 'front'),
  ('ClojureScript', 'front'),
  ('WebAssembly', 'front'),
  ('Python', 'back'),
  ('Java', 'back'),
  ('C#', 'back'),
  ('PHP', 'back'),
  ('Go', 'back'),
  ('Rust', 'back'),
  ('Ruby', 'back'),
  ('Kotlin', 'back'),
  ('Scala', 'back'),
  ('Elixir', 'back'),
  ('Erlang', 'back'),
  ('Clojure', 'back'),
  ('Groovy', 'back'),
  ('Haskell', 'back'),
  ('F#', 'back'),
  ('C++', 'back'),
  ('C', 'back'),
  ('Perl', 'back'),
  ('Lua', 'back'),
  ('Bun', 'back'),
  ('Deno', 'back'),
  ('Express', 'back'),
  ('Fastify', 'back'),
  ('NestJS', 'back'),
  ('AdonisJS', 'back'),
  ('Feathers', 'back'),
  ('Kraken', 'back'),
  ('Moleculer', 'back'),
  ('Socket.IO', 'back'),
  ('GraphQL', 'back'),
  ('gRPC', 'back'),
  ('Flask', 'back'),
  ('FastAPI', 'back'),
  ('Django REST Framework', 'back'),
  ('Spring', 'back'),
  ('Quarkus', 'back'),
  ('Vert.x', 'back'),
  ('Dropwizard', 'back'),
  ('Akka', 'back'),
  ('Ktor', 'back'),
  ('.NET Core', 'back'),
  ('.NET', 'back'),
  ('Lumen', 'back'),
  ('CodeIgniter', 'back'),
  ('CakePHP', 'back'),
  ('Yii', 'back'),
  ('Laminas (Zend)', 'back'),
  ('Phalcon', 'back'),
  ('MySQL', 'back'),
  ('MariaDB', 'back'),
  ('SQLite', 'back'),
  ('SQL Server', 'back'),
  ('Oracle Database', 'back'),
  ('MongoDB', 'back'),
  ('Redis', 'back'),
  ('Cassandra', 'back'),
  ('CouchDB', 'back'),
  ('Couchbase', 'back'),
  ('Neo4j', 'back'),
  ('DynamoDB', 'back'),
  ('Elasticsearch', 'back'),
  ('InfluxDB', 'back'),
  ('Cosmos DB', 'back'),
  ('Fauna', 'back'),
  ('YugabyteDB', 'back'),
  ('RabbitMQ', 'back'),
  ('Kafka', 'back'),
  ('Prisma', 'back'),
  ('Sequelize', 'back'),
  ('Mongoose', 'back'),
  ('Knex.js', 'back'),
  ('SQLAlchemy', 'back'),
  ('Hibernate', 'back'),
  ('Doctrine', 'back'),
  ('NHibernate', 'back'),
  ('Ecto', 'back'),
  ('Jest', 'back'),
  ('Mocha', 'back'),
  ('JUnit', 'back'),
  ('pytest', 'back'),
  ('RSpec', 'back'),
  ('Next.js', 'fullstack'),
  ('Nuxt', 'fullstack'),
  ('Meteor', 'fullstack'),
  ('Blazor', 'fullstack'),
  ('Ruby on Rails', 'fullstack'),
  ('Django', 'fullstack'),
  ('Phoenix', 'fullstack'),
  ('Grails', 'fullstack'),
  ('Livewire', 'fullstack'),
  ('tRPC', 'fullstack'),
  ('Firebase', 'fullstack'),
  ('Supabase', 'fullstack'),
  ('Appwrite', 'fullstack'),
  ('Vue Storefront', 'fullstack');
